name = "wial-country-platform"
main = ".open-next/worker.js"
compatibility_date = "2025-03-29"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "wial-country-platform"
