import type { Coach, Chapter, Event, CertificationProgram, Testimonial } from './types'

export const chapters: Chapter[] = [
  {
    id: '1',
    name: 'WIAL USA',
    slug: 'usa',
    country: 'United States',
    region: 'North America',
    description: 'The founding chapter of WIAL, serving the United States with world-class Action Learning programs and certified coaches.',
    primary_language: 'en',
    supported_languages: ['en', 'es'],
    timezone: 'America/New_York',
    currency: 'USD',
    contact_email: 'usa@wial.org',
    website_url: 'https://wial.org/usa',
    is_active: true,
    founded_year: 1995,
    member_count: 450,
  },
  {
    id: '2',
    name: 'WIAL Nigeria',
    slug: 'nigeria',
    country: 'Nigeria',
    region: 'Africa',
    description: 'Leading Action Learning transformation across West Africa with culturally-adapted programs.',
    primary_language: 'en',
    supported_languages: ['en', 'yo', 'ha', 'ig'],
    timezone: 'Africa/Lagos',
    currency: 'NGN',
    contact_email: 'nigeria@wial.org',
    is_active: true,
    founded_year: 2008,
    member_count: 120,
  },
  {
    id: '3',
    name: 'WIAL Japan',
    slug: 'japan',
    country: 'Japan',
    region: 'Asia Pacific',
    description: 'Bringing Action Learning methodology to Japanese organizations with cultural sensitivity and precision.',
    description_local: '日本の組織にアクションラーニング手法を文化的配慮と精密さをもって導入',
    primary_language: 'ja',
    supported_languages: ['ja', 'en'],
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    contact_email: 'japan@wial.org',
    is_active: true,
    founded_year: 2003,
    member_count: 280,
  },
  {
    id: '4',
    name: 'WIAL Brazil',
    slug: 'brazil',
    country: 'Brazil',
    region: 'South America',
    description: 'Transforming leadership development across Brazil and Portuguese-speaking markets.',
    description_local: 'Transformando o desenvolvimento de liderança no Brasil e mercados lusófonos.',
    primary_language: 'pt',
    supported_languages: ['pt', 'en', 'es'],
    timezone: 'America/Sao_Paulo',
    currency: 'BRL',
    contact_email: 'brazil@wial.org',
    is_active: true,
    founded_year: 2005,
    member_count: 195,
  },
  {
    id: '5',
    name: 'WIAL UK',
    slug: 'uk',
    country: 'United Kingdom',
    region: 'Europe',
    description: 'Serving the UK and Ireland with innovative Action Learning solutions for modern organizations.',
    primary_language: 'en',
    supported_languages: ['en'],
    timezone: 'Europe/London',
    currency: 'GBP',
    contact_email: 'uk@wial.org',
    is_active: true,
    founded_year: 2001,
    member_count: 310,
  },
  {
    id: '6',
    name: 'WIAL South Korea',
    slug: 'south-korea',
    country: 'South Korea',
    region: 'Asia Pacific',
    description: 'Leading Action Learning adoption in Korean corporations and educational institutions.',
    description_local: '한국 기업 및 교육 기관의 액션러닝 도입을 선도합니다.',
    primary_language: 'ko',
    supported_languages: ['ko', 'en'],
    timezone: 'Asia/Seoul',
    currency: 'KRW',
    contact_email: 'korea@wial.org',
    is_active: true,
    founded_year: 2004,
    member_count: 340,
  },
]

export const coaches: Coach[] = [
  {
    id: '1',
    first_name: 'Sarah',
    last_name: 'Mitchell',
    email: 'sarah.mitchell@wial.org',
    bio: 'With over 15 years of experience in organizational development, Sarah specializes in executive coaching and team transformation. She has worked with Fortune 500 companies across North America.',
    specializations: ['Executive Coaching', 'Team Development', 'Change Management'],
    languages: ['English', 'Spanish'],
    country: 'United States',
    city: 'New York',
    chapter_id: '1',
    chapter_name: 'WIAL USA',
    certification_level: 'MALC',
    certification_date: '2018-06-15',
    is_active: true,
    linkedin_url: 'https://linkedin.com/in/sarahmitchell',
  },
  {
    id: '2',
    first_name: 'Oluwaseun',
    last_name: 'Adeyemi',
    email: 'seun.adeyemi@wial.org',
    bio: 'A passionate advocate for African leadership development, Oluwaseun has trained over 500 leaders across West Africa in Action Learning methodologies.',
    specializations: ['Leadership Development', 'Cross-Cultural Training', 'NGO Consulting'],
    languages: ['English', 'Yoruba', 'French'],
    country: 'Nigeria',
    city: 'Lagos',
    chapter_id: '2',
    chapter_name: 'WIAL Nigeria',
    certification_level: 'CALC',
    certification_date: '2019-03-22',
    is_active: true,
  },
  {
    id: '3',
    first_name: 'Yuki',
    last_name: 'Tanaka',
    email: 'yuki.tanaka@wial.org',
    bio: 'Yuki brings a unique blend of traditional Japanese business wisdom and modern Action Learning techniques to her coaching practice. She has helped dozens of Japanese corporations embrace transformative learning.',
    specializations: ['Corporate Training', 'Innovation Workshops', 'Cultural Integration'],
    languages: ['Japanese', 'English'],
    country: 'Japan',
    city: 'Tokyo',
    chapter_id: '3',
    chapter_name: 'WIAL Japan',
    certification_level: 'MALC',
    certification_date: '2016-09-10',
    is_active: true,
  },
  {
    id: '4',
    first_name: 'Carlos',
    last_name: 'Santos',
    email: 'carlos.santos@wial.org',
    bio: 'Carlos is a dynamic facilitator with expertise in startup ecosystems and entrepreneurial leadership. He has trained leaders across Brazil and Latin America.',
    specializations: ['Entrepreneurship', 'Startup Coaching', 'Agile Leadership'],
    languages: ['Portuguese', 'English', 'Spanish'],
    country: 'Brazil',
    city: 'São Paulo',
    chapter_id: '4',
    chapter_name: 'WIAL Brazil',
    certification_level: 'CALC',
    certification_date: '2020-01-18',
    is_active: true,
  },
  {
    id: '5',
    first_name: 'Emma',
    last_name: 'Thompson',
    email: 'emma.thompson@wial.org',
    bio: 'A former HR director at major UK corporations, Emma now dedicates her career to developing the next generation of leaders through Action Learning.',
    specializations: ['HR Strategy', 'Talent Development', 'Diversity & Inclusion'],
    languages: ['English'],
    country: 'United Kingdom',
    city: 'London',
    chapter_id: '5',
    chapter_name: 'WIAL UK',
    certification_level: 'MALC',
    certification_date: '2017-11-05',
    is_active: true,
    linkedin_url: 'https://linkedin.com/in/emmathompson',
  },
  {
    id: '6',
    first_name: 'Min-jun',
    last_name: 'Kim',
    email: 'minjun.kim@wial.org',
    bio: 'Min-jun specializes in transforming traditional Korean corporate cultures through innovative Action Learning approaches. He has worked with Samsung, Hyundai, and numerous SMEs.',
    specializations: ['Corporate Culture', 'Digital Transformation', 'Strategic Planning'],
    languages: ['Korean', 'English', 'Mandarin'],
    country: 'South Korea',
    city: 'Seoul',
    chapter_id: '6',
    chapter_name: 'WIAL South Korea',
    certification_level: 'MALC',
    certification_date: '2015-04-20',
    is_active: true,
  },
  {
    id: '7',
    first_name: 'Maria',
    last_name: 'Rodriguez',
    email: 'maria.rodriguez@wial.org',
    bio: 'Maria brings 20 years of corporate experience to her coaching practice, specializing in helping organizations navigate complex change initiatives.',
    specializations: ['Change Management', 'Executive Development', 'Team Building'],
    languages: ['English', 'Spanish'],
    country: 'United States',
    city: 'Miami',
    chapter_id: '1',
    chapter_name: 'WIAL USA',
    certification_level: 'CALC',
    certification_date: '2021-08-12',
    is_active: true,
  },
  {
    id: '8',
    first_name: 'James',
    last_name: 'Chen',
    email: 'james.chen@wial.org',
    bio: 'James bridges Eastern and Western business practices, helping multinational teams collaborate more effectively through Action Learning.',
    specializations: ['Cross-Cultural Leadership', 'Global Teams', 'Communication'],
    languages: ['English', 'Mandarin', 'Japanese'],
    country: 'United States',
    city: 'San Francisco',
    chapter_id: '1',
    chapter_name: 'WIAL USA',
    certification_level: 'SALC',
    certification_date: '2023-02-28',
    is_active: true,
  },
]

export const events: Event[] = [
  {
    id: '1',
    title: 'SALC Certification Workshop',
    description: 'Begin your journey as a certified Action Learning Coach. This intensive 3-day workshop covers the fundamentals of Action Learning methodology.',
    event_type: 'workshop',
    start_date: '2026-04-15',
    end_date: '2026-04-17',
    timezone: 'America/New_York',
    location_type: 'in_person',
    venue_name: 'WIAL USA Headquarters',
    venue_address: '123 Leadership Way, New York, NY 10001',
    chapter_id: '1',
    chapter_name: 'WIAL USA',
    max_attendees: 25,
    current_attendees: 18,
    price_amount: 1500,
    price_currency: 'USD',
    is_free: false,
    registration_deadline: '2026-04-08',
    status: 'published',
  },
  {
    id: '2',
    title: 'Introduction to Action Learning Webinar',
    description: 'A free introductory session for those curious about Action Learning. Learn the basics and see how it can transform your organization.',
    event_type: 'webinar',
    start_date: '2026-04-05',
    timezone: 'Europe/London',
    location_type: 'online',
    online_meeting_url: 'https://zoom.us/j/example',
    chapter_id: '5',
    chapter_name: 'WIAL UK',
    max_attendees: 100,
    current_attendees: 67,
    is_free: true,
    status: 'published',
  },
  {
    id: '3',
    title: 'WIAL Global Conference 2026',
    description: 'Our annual gathering of Action Learning professionals from around the world. Three days of learning, networking, and inspiration.',
    event_type: 'conference',
    start_date: '2026-09-20',
    end_date: '2026-09-22',
    timezone: 'Asia/Tokyo',
    location_type: 'hybrid',
    venue_name: 'Tokyo International Forum',
    venue_address: '3-5-1 Marunouchi, Chiyoda City, Tokyo',
    online_meeting_url: 'https://wial.org/conference/virtual',
    chapter_id: '3',
    chapter_name: 'WIAL Japan',
    max_attendees: 500,
    current_attendees: 234,
    price_amount: 750,
    price_currency: 'USD',
    is_free: false,
    registration_deadline: '2026-09-01',
    status: 'published',
  },
  {
    id: '4',
    title: 'Action Learning for African Leaders',
    description: 'A specialized training program designed for leaders working in the African context, addressing unique challenges and opportunities.',
    event_type: 'training',
    start_date: '2026-05-10',
    end_date: '2026-05-12',
    timezone: 'Africa/Lagos',
    location_type: 'in_person',
    venue_name: 'Lagos Business School',
    venue_address: 'Km 22 Lekki-Epe Expressway, Lagos',
    chapter_id: '2',
    chapter_name: 'WIAL Nigeria',
    max_attendees: 30,
    current_attendees: 22,
    price_amount: 500,
    price_currency: 'USD',
    is_free: false,
    registration_deadline: '2026-05-03',
    status: 'published',
  },
  {
    id: '5',
    title: 'Monthly Coach Meetup - Seoul',
    description: 'Join fellow WIAL coaches for an informal gathering to share experiences, challenges, and best practices.',
    event_type: 'meetup',
    start_date: '2026-04-25',
    timezone: 'Asia/Seoul',
    location_type: 'in_person',
    venue_name: 'Gangnam Coach Hub',
    venue_address: '123 Teheran-ro, Gangnam-gu, Seoul',
    chapter_id: '6',
    chapter_name: 'WIAL South Korea',
    max_attendees: 20,
    current_attendees: 12,
    is_free: true,
    status: 'published',
  },
  {
    id: '6',
    title: 'CALC Advanced Certification',
    description: 'Advance your coaching skills with the Certified Action Learning Coach certification. Prerequisites: SALC certification and 50+ coaching hours.',
    event_type: 'training',
    start_date: '2026-06-01',
    end_date: '2026-06-05',
    timezone: 'America/Sao_Paulo',
    location_type: 'in_person',
    venue_name: 'WIAL Brazil Training Center',
    venue_address: 'Av. Paulista, 1000, São Paulo',
    chapter_id: '4',
    chapter_name: 'WIAL Brazil',
    max_attendees: 15,
    current_attendees: 8,
    price_amount: 2500,
    price_currency: 'USD',
    is_free: false,
    registration_deadline: '2026-05-15',
    status: 'published',
  },
]

export const certificationPrograms: CertificationProgram[] = [
  {
    id: '1',
    name: 'Student Action Learning Coach',
    slug: 'salc',
    level: 'SALC',
    description: 'The foundational certification for aspiring Action Learning coaches. Learn the core methodology and begin your journey as a facilitator of transformative learning experiences.',
    requirements: [
      'Complete 3-day SALC workshop',
      'Pass written assessment',
      'Demonstrate basic facilitation skills',
      'Submit reflection paper',
    ],
    duration_weeks: 1,
    price_usd: 1500,
    learning_outcomes: [
      'Understand Action Learning theory and principles',
      'Facilitate basic Action Learning sessions',
      'Apply questioning techniques effectively',
      'Create psychological safety in groups',
      'Structure problem-solving conversations',
    ],
  },
  {
    id: '2',
    name: 'Certified Action Learning Coach',
    slug: 'calc',
    level: 'CALC',
    description: 'The intermediate certification demonstrating proficiency in Action Learning facilitation. Ideal for coaches ready to work with organizations professionally.',
    requirements: [
      'Hold SALC certification',
      'Complete 50+ hours of coaching practice',
      'Attend 2-day CALC advanced workshop',
      'Pass practical assessment',
      'Submit portfolio of 3 case studies',
      'Receive positive peer reviews',
    ],
    duration_weeks: 12,
    price_usd: 2500,
    learning_outcomes: [
      'Design custom Action Learning programs',
      'Handle complex group dynamics',
      'Coach organizational leaders effectively',
      'Measure and report program outcomes',
      'Adapt methodology to cultural contexts',
      'Build sustainable learning cultures',
    ],
    prerequisites: ['SALC certification', 'Minimum 50 coaching hours'],
  },
  {
    id: '3',
    name: 'Master Action Learning Coach',
    slug: 'malc',
    level: 'MALC',
    description: 'The highest level of WIAL certification, recognizing mastery in Action Learning practice. MALC coaches lead complex organizational transformations and train other coaches.',
    requirements: [
      'Hold CALC certification for 2+ years',
      'Complete 200+ hours of professional coaching',
      'Attend MALC intensive retreat',
      'Submit master thesis on Action Learning',
      'Pass comprehensive oral examination',
      'Demonstrate thought leadership in the field',
      'Train and mentor at least 5 SALC candidates',
    ],
    duration_weeks: 24,
    price_usd: 5000,
    learning_outcomes: [
      'Lead enterprise-wide transformation initiatives',
      'Design certification programs for organizations',
      'Contribute to Action Learning research',
      'Train and certify other coaches',
      'Consult at C-suite level',
      'Adapt methodology for diverse industries',
      'Build and lead coaching communities',
    ],
    prerequisites: ['CALC certification for 2+ years', 'Minimum 200 coaching hours', 'Mentor experience'],
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    author_name: 'Jennifer Park',
    author_title: 'VP of Learning & Development',
    author_company: 'Global Tech Corp',
    content: 'WIAL transformed how we approach leadership development. Our Action Learning programs have directly contributed to a 40% improvement in leadership effectiveness scores.',
    rating: 5,
    chapter_id: '1',
  },
  {
    id: '2',
    author_name: 'Takeshi Yamamoto',
    author_title: 'Chief Human Resources Officer',
    author_company: 'Yamamoto Industries',
    content: 'The cultural sensitivity of WIAL Japan coaches made all the difference. They understood our unique needs and delivered results that exceeded our expectations.',
    rating: 5,
    chapter_id: '3',
  },
  {
    id: '3',
    author_name: 'Amara Okonkwo',
    author_title: 'Executive Director',
    author_company: 'African Leadership Foundation',
    content: 'WIAL Nigeria has been instrumental in developing the next generation of African leaders. Their approach respects our values while pushing us to grow.',
    rating: 5,
    chapter_id: '2',
  },
  {
    id: '4',
    author_name: 'Michael Richards',
    author_title: 'CEO',
    author_company: 'Richards Consulting',
    content: 'Becoming a MALC was the best investment I made in my career. The methodology is powerful, and the global network of coaches is invaluable.',
    rating: 5,
    program_id: '3',
  },
  {
    id: '5',
    author_name: 'Sofia Martinez',
    author_title: 'Learning Manager',
    author_company: 'Brazilian Banking Group',
    content: 'Our teams learned more in one Action Learning session than in months of traditional training. The ROI is undeniable.',
    rating: 5,
    chapter_id: '4',
  },
]

export const stats = {
  totalCoaches: 2500,
  countriesActive: 47,
  organizationsTrained: 1200,
  yearsExperience: 30,
}

export const specializations = [
  'Executive Coaching',
  'Team Development',
  'Change Management',
  'Leadership Development',
  'Cross-Cultural Training',
  'NGO Consulting',
  'Corporate Training',
  'Innovation Workshops',
  'Cultural Integration',
  'Entrepreneurship',
  'Startup Coaching',
  'Agile Leadership',
  'HR Strategy',
  'Talent Development',
  'Diversity & Inclusion',
  'Corporate Culture',
  'Digital Transformation',
  'Strategic Planning',
]

export const languages = [
  'English',
  'Spanish',
  'Portuguese',
  'French',
  'Japanese',
  'Korean',
  'Mandarin',
  'Yoruba',
  'Hausa',
  'Igbo',
]

export const countries = [
  'United States',
  'United Kingdom',
  'Nigeria',
  'Japan',
  'Brazil',
  'South Korea',
]
